/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as BoardNewRouteImport } from './routes/board/new'
import { Route as BoardThreadIdRouteImport } from './routes/board/$threadId'
import { Route as BoardThreadIdIndexRouteImport } from './routes/board/$threadId/index'
import { Route as BoardThreadIdNewRouteImport } from './routes/board/$threadId/new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardNewRoute = BoardNewRouteImport.update({
  id: '/board/new',
  path: '/board/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardThreadIdRoute = BoardThreadIdRouteImport.update({
  id: '/board/$threadId',
  path: '/board/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardThreadIdIndexRoute = BoardThreadIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardThreadIdRoute,
} as any)
const BoardThreadIdNewRoute = BoardThreadIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BoardThreadIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/board/$threadId': typeof BoardThreadIdRouteWithChildren
  '/board/new': typeof BoardNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/board/': typeof BoardIndexRoute
  '/board/$threadId/new': typeof BoardThreadIdNewRoute
  '/board/$threadId/': typeof BoardThreadIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/board/new': typeof BoardNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/board': typeof BoardIndexRoute
  '/board/$threadId/new': typeof BoardThreadIdNewRoute
  '/board/$threadId': typeof BoardThreadIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/board/$threadId': typeof BoardThreadIdRouteWithChildren
  '/board/new': typeof BoardNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/board/': typeof BoardIndexRoute
  '/board/$threadId/new': typeof BoardThreadIdNewRoute
  '/board/$threadId/': typeof BoardThreadIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/board/$threadId'
    | '/board/new'
    | '/profile/$userId'
    | '/board/'
    | '/board/$threadId/new'
    | '/board/$threadId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/board/new'
    | '/profile/$userId'
    | '/board'
    | '/board/$threadId/new'
    | '/board/$threadId'
  id:
    | '__root__'
    | '/'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/board/$threadId'
    | '/board/new'
    | '/profile/$userId'
    | '/board/'
    | '/board/$threadId/new'
    | '/board/$threadId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BoardThreadIdRoute: typeof BoardThreadIdRouteWithChildren
  BoardNewRoute: typeof BoardNewRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/new': {
      id: '/board/new'
      path: '/board/new'
      fullPath: '/board/new'
      preLoaderRoute: typeof BoardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$threadId': {
      id: '/board/$threadId'
      path: '/board/$threadId'
      fullPath: '/board/$threadId'
      preLoaderRoute: typeof BoardThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$threadId/': {
      id: '/board/$threadId/'
      path: '/'
      fullPath: '/board/$threadId/'
      preLoaderRoute: typeof BoardThreadIdIndexRouteImport
      parentRoute: typeof BoardThreadIdRoute
    }
    '/board/$threadId/new': {
      id: '/board/$threadId/new'
      path: '/new'
      fullPath: '/board/$threadId/new'
      preLoaderRoute: typeof BoardThreadIdNewRouteImport
      parentRoute: typeof BoardThreadIdRoute
    }
  }
}

interface BoardThreadIdRouteChildren {
  BoardThreadIdNewRoute: typeof BoardThreadIdNewRoute
  BoardThreadIdIndexRoute: typeof BoardThreadIdIndexRoute
}

const BoardThreadIdRouteChildren: BoardThreadIdRouteChildren = {
  BoardThreadIdNewRoute: BoardThreadIdNewRoute,
  BoardThreadIdIndexRoute: BoardThreadIdIndexRoute,
}

const BoardThreadIdRouteWithChildren = BoardThreadIdRoute._addFileChildren(
  BoardThreadIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BoardThreadIdRoute: BoardThreadIdRouteWithChildren,
  BoardNewRoute: BoardNewRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  BoardIndexRoute: BoardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
